@startuml
title 基于GitHub的实验管理平台--学生列表顺序图
actor TEACHERS
activate TEACHERS
TEACHERS -> 主界面: 1.教师登录
activate 主界面
主界面->科目详情:2.请求查看学生名单
activate 科目详情
database 服务器
database 数据库存储
科目详情 -> 服务器:3.请求查看学生名单
activate 服务器
服务器-> 数据库存储:4.请求查看学生名单
activate 数据库存储
数据库存储->主界面:5.返回学生名单
deactivate 数据库存储
deactivate 服务器
deactivate 主界面
deactivate 科目详情
deactivate TEACHERS
@enduml