@startwbs
* 基于GitHub的实验管理平台
** 学生
*** 登录
*** 注册
*** 查成绩
*** 选课
*** 维护个人信息
*** 修改密码
** 教师
*** 登录
*** 注册
*** 成绩列表
*** 选课
*** 维护个人信息
*** 修改密码
*** 维护评分细则
*** 发布实验
*** 修改实验
*** 删除实验
@endwbs