@startuml
title 基于GitHub的实验管理平台--课程列表顺序图
actor USER
activate USER
USER -> 主界面: 1.用户登录
activate 主界面
database 服务器
database 数据库存储
主界面->服务器:2.选择学期
activate 服务器
服务器-> 数据库存储:4.请求查看课程列表
activate 数据库存储
数据库存储->主界面:5.返回课程列表
deactivate 数据库存储
deactivate 服务器
deactivate 主界面
deactivate USER
@enduml