@startuml
title 基于GitHub的实验管理平台--选课用例的顺序图
actor USERS
activate USERS
USERS -> 选课界面: 1.发送选课请求
activate 选课界面
database 服务器
database 数据库存储
选课界面 -> 服务器:2.发送选课请求
activate 服务器
服务器-> 数据库存储:3.查询课程信息
activate 数据库存储
数据库存储->服务器:4.返回课程信息
deactivate 数据库存储
服务器->服务器:5.判断是否符合选课资格
服务器->选课界面:6.发送确认信息
deactivate 服务器
选课界面->USERS:7.显示确认框
USERS->选课界面:8.点击确认
选课界面 -> 服务器:9.发送确认信息
activate 服务器
服务器-> 数据库存储:10.更新数据库
activate 数据库存储
数据库存储 -> USERS:11.返回选课结果
deactivate 数据库存储
deactivate 服务器
deactivate 选课界面
deactivate USERS
@enduml